version: '2'

services:
  cc-port:
    image: ghcr.io/clcarter/cc-port:latest
    restart: unless-stopped
    ports: 
      - "3000:3000"
    networks:
      cwproxy:
        ipv4_address: ${IPV4_SERVER}

networks:
  cwproxy:
    name: cwproxy
    external: true
